version: '3.8'
services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - URLS=http://+:5000
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    ports:
      - "5000:5000"
    command: dotnet run --urls=http://+:5000