version: '3.8'
services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - URLS=http://+:5000
    ports:
      - "5000:5000"
    command: dotnet run